# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# --------------------------------------------------------------------------------
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# --------------------------------------------------------------------------------

title: kunihiro's sphere
email: lanwireless@outlook.com
description: >- # this means to ignore newlines until "url:"
  Nothing
url: Linoleum2609.github.io # the base hostname & protocol for your site

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
remote_theme: Linoleum2609/Linoleum2609.github.io
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

dash:
  date_format: "%b %-d, %Y"

  giscus:
    repo: Linoleum2609/Linoleum2609.github.io

  # generate social links
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  # Check https://icon-sets.iconify.design
  social_links:
    - url: https://twitter.com/krypterad_
      icon: simple-icons:twitter
      color: cyan
    - url: https://github.com/Linoleum2609
      icon: simple-icons:github
      color: purple
    - url: https://osu.ppy.sh/users/9829957
      icon: simple-icons:osu
      color: pink

  show_author: true
